# Generated by Django 5.2.1 on 2025-05-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
